version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gradeitDB
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: gradeit
    ports:
      - "5173:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  gradeit-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gradeit_node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgresql://gradeitDB:mypassword@db:5432/gradeit
    depends_on:
      - db
volumes:
  gradeit_node_modules:
  db_data:
